### ISSUE TITLE
Latest v0.1.3 breaks with Multiple dex files define Lcom/google/android/gms/iid/MessengerCompat$1;

### ISSUE THREAD

**Issue by sebawagner** [irvingdp/react-native-gtm#4]
Hi,

when using the latest v0.1.3 version and "react-native": "^0.31.0"

It breaks with the attached exception.

I think the issue is that the latest GTM requires Play Store 9.4.0, while some other plugins require older Google Play Store versions. You can essentially I think not mix dependencies that have Play Store 8.4.0 and 9.4.0 mixed.

Exception during Gradle build:
10:32:17 Dex: Error converting bytecode to dex:
10:32:17 Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/iid/MessengerCompat$1;
10:32:17     UNEXPECTED TOP-LEVEL EXCEPTION:
10:32:17     com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/iid/MessengerCompat$1;
10:32:17     	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
10:32:17     	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
10:32:17     	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
10:32:17     	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
10:32:17     	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
10:32:17     	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
10:32:17     	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
10:32:17     	at com.android.dx.command.dexer.Main.run(Main.java:277)
10:32:17     	at com.android.dx.command.dexer.Main.main(Main.java:245)
10:32:17     	at com.android.dx.command.Main.main(Main.java:106)

**Comment by carera** [comment]
Remove fixed version of gcm library in android/app/build.gradle 
e.g. find the
`compile ('com.google.android.gms:play-services-gcm:8.1.0')`
and change it to 
`compile ('com.google.android.gms:play-services-gcm:+')`
